Homework2
made-ml-in-prod-2021/vbakulev pull request #3
Opened 2021-05-18 18:37 UTC by vbakulev

2021-05-22 18:43 UTC, Mikhail-M requested changes
в реквесте код от первой дз, которого быть не должно

2021-05-23 14:21 UTC, ioiein reviewed
Сервис реализован корректно, работает как и через uvicorn run, так и при помощи docker.
По всем пунктам самоанализа автора задания выполнены. Согласен с оценкой 16 балов.
Из небольших придирок: в коде имеются unused import, при запуске проекта pycharm сразу начал на это указывать.

2021-05-23 14:21 UTC, ioiein commented on online_inference/app.py
> +from typing import List, Union, Optional
unused import List, Union

2021-05-23 14:21 UTC, ioiein commented on online_inference/src/models/app_data.py
> +from typing import List, Union, Optional
unused import

2021-05-23 14:21 UTC, ioiein commented on online_inference/src/models/utils.py
> +from typing import List, Union, Optional
unused import

2021-05-23 14:21 UTC, ioiein commented on online_inference/make_request.py
> +            "http://127.0.0.1:8000/predict/",
Если не ошибаюсь, то если сделать так "http://localhost:8000/predict/", то не должно быть проблем при разных ОС.

2021-06-01 20:02 UTC, vbakulev commented on online_inference/make_request.py
> +            "http://127.0.0.1:8000/predict/",
Проверил. Действительно работает

2021-06-09 18:01 UTC, ioiein approved these changes

2021-06-12 10:20 UTC, Mikhail-M approved these changes
Баллы: 15

За тесты -- 2 балла

2021-06-14 16:04 UTC, merged