Homework3
made-ml-in-prod-2021/vbakulev pull request #4
Opened 2021-06-09 17:03 UTC by vbakulev

![all_dars](https://user-images.githubusercontent.com/70772962/121398029-99898480-c95d-11eb-96c5-df2d94ae6721.png)
![graph_for_dag_01_generate_data](https://user-images.githubusercontent.com/70772962/121398037-9abab180-c95d-11eb-82bb-ac961e4dbb8d.png)
![graph_for_dag_02_train](https://user-images.githubusercontent.com/70772962/121398043-9b534800-c95d-11eb-82fa-704fe834d231.png)
![graph_for_dag_03_predict](https://user-images.githubusercontent.com/70772962/121398048-9bebde80-c95d-11eb-8674-06c5a9384a0c.png)

2021-06-13 17:43 UTC, Mikhail-M requested changes
Приведите ревью в порядок
не нужно, чтобы были удаленные файлы, csv тоже не нужны

2021-06-13 23:48 UTC, vladimirzenin approved these changes
Успешно поднял ваш код локально, 2 дага прошли, последний не смог импортироваться, возможно я не разобрался. Вижу на ваших скриншотах все работает.
Для первых двух вижу ожидаемые файлы.
Даги и образы описаны корректно.
Тесты есть.
36 баллов

2021-06-21 14:45 UTC, closed without merging

2021-06-22 19:55 UTC, vbakulev commented
@Mikhail-M 
Ненужные csv удалил, но в попытке почистить PR путем необдуманных манипуляций закрыл ветку. Решения как восстановить найти не могу и с учетом длительного времени после дедлайна не успею. Да и не хочется случайно удалить ревью. Понимаю, что будет большой штраф, но хотелось бы получить хоть какие-то баллы

2021-06-28 18:44 UTC, Mikhail-M commented
баллы 30